site_name: MathBioLab at UMass Boston
theme:
  name: material
  logo: assets/images/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
  custom_dir: overrides
  extra_css:
    - assets/stylesheets/extra.css
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: white
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: /
  - Research:
    - Overview: research/overview.md
    - Projects: research/projects.md
    - Computational Methods: research/methods.md
  - People:
    - Lab Members: people/index.md
    - By Research Interest: people/by-research.md
  - Publications:
    - publications/index.md
  - News & Events:
    - news/index.md
  - About: about/
  - Contact: contact/

plugins:
  - meta
  - search
  - tags:
      scope: true
      tags_hierarchy: true
  - blog:
      blog_dir: news
      blog_toc: true
      post_dir: "{blog}/posts"
      post_date_format: medium
      post_url_format: "{date}/{slug}"
      categories: true
      categories_name: Categories
      archive: true
      archive_name: Archive
      pagination_per_page: 5
      authors_file: "{blog}/.authors.yml"
  - blog:
      blog_dir: publications
      blog_toc: true
      post_dir: "{blog}/papers"
      post_date_format: medium
      post_url_format: "{date}/{slug}"
      categories: true
      categories_name: Topics
      archive: true
      archive_name: "Publication Year"
      pagination_per_page: 5
      authors_file: "{blog}/.authors.yml"

markdown_extensions:
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - pymdownx.blocks.caption

